-- help.lua ======= 2224

-- Common help section shared by all three modes (save formats, display modes, symbols, fonts)

function showHelpCommon()
   echoW("SAVE-GAME FORMATS:")
   print("-------------")
   print("Load accepts these")
   print("save-game formats (Examples):")
   print("")
   print("1) Full save:")
   print("-------------")
   print("c:11|bc:11|ep:0|last:e7e6|ucap:-|ecap:-|wm:2|bm:2|hc:0|next:w|hist:b1c3,g8f6,g1f3,e7e6|start:rnbqkbnr;pppppppp;8;8;8;8;PPPPPPPP;RNBQKBNR|board:rnbqkb1r;pppp1ppp;4pn2;8;8;2N2N2;PPPPPPPP;R1BQKB1R")
   print("-------------")
   print("• Full format restores game state and history.")
   print("")
   print("2) Board save:")
   print("-------------")
   print("board:rnbqkb1r;pppp1ppp;4pn2;8;8;2N2N2;PPPPPPPP;R1BQKB1R")
   print("-------------")
   print("")
   print("3) Plain 8x8 board")
   print("-------------")
   print("rnbqkb.r\npppp.ppp\n....pn..\n........\n........\n..N..N..\nPPPPPPPP\nR.BQKB.R")
   print("-------------")
   print("• Formats 2 and 3 load a board position only.")
   print("• Puzzle load accepts formats 2 and 3.")
   print("")
   echoW("GAME RULES / DRAW DETECTION:")
   print("-------------")
   print("• Check, checkmate and stalemate are detected")
   print("• 50-move no-progress draw is automatic")
   print("• Threefold repetition draw is automatic")
   print("• Insufficient-material draws are detected")
   print("• Pawn promotion allows Q, R, B or N")
   print("")
   echoW("DISPLAY MODES:")
   print("-------------")
   print("Unicode mode:")
   print("• Your pieces:    ♚ ♛ ♜ ♝ ♞ ♟")
   print("• Sunfish pieces: ♔ ♕ ♖ ♗ ♘ ♙")
   print("• Empty squares:  • light ◦ dark")
   print("")
   print("Letter mode:")
   print("• Your pieces:    K Q R B N P")
   print("• Sunfish pieces: k q r b n p")
   print("• Empty squares:  : light . dark")
   print("")
   echoW("DEFAULT CONFIGURATION can be changed in CONFIG - section at top of LUA script:")
   print("-------------")
   print("USE_UNICODE_PIECES = true/false")
   print("SHOW_ANNOTATIONS = true/false")
   print("local NODES_SEARCHED = 2000")
   print("local CHALLENGE_ENGINE_NODES = 600")
   print("")
   echoW("PIECE SYMBOLS:")
   print("-------------")
   print("K = King   Q = Queen  R = Rook")
   print("B = Bishop N = Knight P = Pawn")
   print("")
   print("uppercase = Your pieces,")
   print("lowercase = Sunfish.")
   print("")
   echoW("BOARD MARKERS")
   print("(what symbols mean):")
   print("-------------")
   print(" sym! - piece is giving CHECK")
   print("!sym! - piece delivers CHECKMATE")
   print(" sym? - piece GUARDS escape square")
   print("(sym) - piece just moved here")
   print("'sym' - CG hint: suggested move")
   print("      • shown on both")
   print("        the piece to move")
   print("        and its target square")
   print("")
   print("Combined markers:")
   print("(sym! - piece moved AND gives check")
   print("(sym? - piece moved AND guards escape")
   print("")
   print("Note: ( ) shows last move")
   print("!  shows check/checkmate")
   print("?  shows guard")
   print("' ' shows Challenge Game hint")
   print("")
   echoW("RECOMMENDED FONTS:")
   print("-------------")
   print("For Unicode symbols:")
   print("• DejaVu Sans Mono")
   print("• Julia Mono")
   print("• Everson Mono")
   print("• Unifont")
   print("")
   print("For letter mode:")
   print("• Any monospaced font")
   print("")
end

-- Help: normal game

function showHelpGame()
   print("")
   echoW("=== CHESS.LUA HELP ===")
   print("")
   echoW("COMMANDS FOR CHESS:")
   print("-------------")
   print("moves - Enter moves in format 'e2e4'")
   print("'h' - Show this help screen")
   print("'?' - Show About screen")
   print("'d' - Toggle display mode")
   print("    • Unicode symbols <-> Letters.")
   print("'a' - Toggle annotations")
   print("    • show/hide board markers.")
   print("'z' - Undo your last move")
   print("    • also undoes Sunfish's reply")
   print("    • one level only (no re-undo)")
   print("'th' - Toggle hints on/off")
   print("    • shows engine's suggested move")
   print("      as an on-board hint")
   print("'s' - Save current game")
   print("      (generate code)")
   print("'sN' - Save position")
   print("       after history move N")
   print("     • e.g. 's15' saves the position")
   print("       after move 15, even if")
   print("       you have played further.")
   print("     • 's0' saves the starting position.")
   print("'l' - Load saved game")
   print("'nN' - Change engine node budget")
   print("     • e.g. 'n4000'")
   print("     • higher N = harder/slower")
   print("     • lower N = easier/faster")
   print("     • default: n2000")
   print("'m' - Show move history")
   print("'r' - Resign current game")
   print("'n' - Start a new game")
   print("'u' - Check sunfish.lua for updates")
   print("'q' - Quit chess.lua")
   print("")

   showHelpCommon()

   echoW("↑↑↑ CHESS.LUA HELP ↑↑↑")
end

-- Help: mate-in-1 puzzle mode

function showHelpPuzzle()
   print("")
   echoW("=== CHESS.LUA HELP ===")
   print("")
   echoW("COMMANDS FOR PUZZLE MODE:")
   print("-------------")
   print("'m1' - Enter Mate-in-1 puzzle mode")
   print("'h1' - Hint: which piece type mates")
   print("'h2' - Hint: which square to move from")
   print("'h3' - Hint: which square to mate on")
   print("'h4' - Full solution")
   print("'s' - Save current puzzle")
   print("'l' - Load saved puzzle")
   print("'n' - Generate a new puzzle")
   print("'d' - Toggle Unicode / letter display")
   print("'a' - Toggle annotations")
   print("'u' - Check sunfish.lua for updates")
   print("'h' - Show this help screen")
   print("'?' - Show About screen")
   print("'q' - Leave puzzle mode")
   print("")

   showHelpCommon()

   echoW("↑↑↑ CHESS.LUA HELP ↑↑↑")
end

-- Help: Challenge Game mode

function showHelpChallenge()
   print("")
   echoW("=== CHESS.LUA HELP ===")
   print("")
   echoW("COMMANDS FOR CHALLENGE GAME:")
   print("-------------")
   print("'cg' - Enter Challenge Game mode")
   print("     • " .. CHALLENGE_MIN_PIECES .. "-" .. CHALLENGE_MAX_PIECES .. " random pieces,")
   print("       play freely vs Sunfish,")
   print("       no move limit")
   print("     • shows a suggested move")
   print("       as an on-board hint")
   print("       to help you learn")
   print("'th' - Toggle hints on/off")
   print("'z' - Undo your last move")
   print("    • also undoes Sunfish's reply")
   print("    • one level only (no re-undo)")
   print("'r' - Resign this attempt")
   print("'n' - New position")
   print("'q' - Leave Challenge Game mode")
   print("")
   print("• All other commands work the same as in a normal game (s/sN/l/m/h/a/d/u/?)")
   print("")

   showHelpCommon()

   echoW("↑↑↑ CHESS.LUA HELP ↑↑↑")
end

-- Kept for backward-compat: some call sites may still reference the old combined name.
function showHelp()
   showHelpGame()
end

-- About

function showAbout()
   print("")
   echoW("=== ABOUT SUNFISH.LUA ===")
   print("")
   print("Sunfish.lua is a Lua adaptation of Sunfish,")
   print("the compact chess engine originally written")
   print("in Python by Thomas Ahle.")
   print("github.com/thomasahle/sunfish")
   print("")
   print("The original Lua port was made by")
   print("Soumith Chintala.")
   print("github.com/soumith/sunfish.lua")
   print("")
   print("This version is substantially extended")
   print("for Yantra Launcher on Android")
   print("(Luaj-jse 3.0.1) by borko17")
   print("(github.com/borko17), with help from")
   print("Claude AI.")
   print("")
   echoW("PROJECT HERITAGE / LICENSING:")
   print("-------------")
   print("• Thomas Ahle Sunfish: GNU GPL v3")
   print("• Soumith Chintala Lua port: source identifies")
   print("  its code license as BSD")
   print("• This version contains substantial")
   print("  independent modifications and extensions")
   print("")
   echoW("ENGINE EXTENSIONS:")
   print("-------------")
   print("• Node-budget search instead of a timer")
   print("• Adjustable engine strength via 'nN'")
   print("• Smaller, budget-scaled transposition table")
   print("• Zugzwang guard on null-move pruning")
   print("• Endgame king-centralization table")
   print("• Depth-scaled quiescence threshold")
   print("")
   echoW("CHESS FEATURES:")
   print("-------------")
   print("• Legal-move validation")
   print("• Check, checkmate and stalemate detection")
   print("• 50-move-rule draw detection")
   print("• Threefold-repetition draw detection")
   print("• Insufficient-material draw detection")
   print("• Choice of Q, R, B or N on promotion")
   print("• Captured-piece tracking")
   print("• Move history and position snapshots")
   print("• Single-level undo ('z')")
   print("• On-board move hints, toggleable ('th')")
   print("")
   echoW("SAVE / DISPLAY:")
   print("-------------")
   print("• Save and load games via text codes")
   print("• Compact save format")
   print("• Compatibility with the older 8x8 save format")
   print("• Save/load of individual historical positions")
   print("• Unicode or letter piece display")
   print("• Check, guard and last-move board markers")
   print("")
   echoW("PUZZLES / TOOLS:")
   print("-------------")
   print("• Mate-in-1 puzzle generator")
   print("• Puzzle hints and full solutions")
   print("• Puzzle save/load")
   print("• Automatic verification of generated mates")
   print("• Online update checker ('u')")
   print("")
   print("Sunfish.lua remains a compact chess engine,")
   print("but this version also provides a complete")
   print("interactive chess environment for Yantra.")
   print("")
   echoW("↑↑↑ ABOUT SUNFISH.LUA ↑↑↑")
end

-- help.lua ======= end
